defaults:
  - pi0.5_base
  - _self_

robomimic_model:
  camera_transforms: {}
  ac_keys:
    eva_bimanual: "actions_cartesian"
  domains: ["eva_bimanual"]
  action_encoding: "cartesian_ypr_raw_rot6d_v1"

  action_converters:
    rules:
      EVA_BIMANUAL:
        _target_: egomimic.utils.action_utils.RobotBimanualCartesianEuler
    # optional fallback if no match is found
    fallback:
      _target_: egomimic.utils.action_utils.BaseActionConverter

